### Installation

In [ ]:
pip install -r requirements.txt

Install Microsoft Build Tools version 14.0 or greater.

In [ ]:
!pip install numpy==1.17.1
!pip install scipy==1.3.2

In [ ]:
pip install --upgrade setuptools wheel

In [ ]:
pip install --upgrade numpy==1.17.1

In [ ]:
pip install hdbscan==0.8.24

### Run Code

In [60]:
import os
# path = "C:\\Users\\KIIT\\Desktop\\Videos"
path = "C:\\Users\\KIIT\\Desktop\\College\\Animall\\key_frame_extraction_public-master"
for img in os.listdir(path):
    if img.endswith(".mp4"):
        !python candidate_frames_folder.py --input_videos {img} --output_folder_video_image candidate_frames_and_their_cluster_folder --output_folder_video_final_image final_images

[0 0 0 1 0 2 2 0 2 0 1 1 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0]
36
[-1  0  1]
[[array([ 3, 10, 11, 12, 13, 22, 23], dtype=int64)]
 [array([5, 6, 8], dtype=int64)]]
files_clusters_index_array_of_only_one_image:  [(array([ 0,  1,  2,  4,  7,  9, 14, 15, 16, 17, 18, 19, 20, 21, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35], dtype=int64),)]
Final List:  [ 0  1  2  4  5  7  9 13 14 15 16 17 18 19 20 21 24 25 26 27 28 29 30 31
 32 33 34 35]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 0 1 1 1 2 2 2 2 2 2 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1]
84
[-1  0  1]
[[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 24, 27, 28,
         29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 43, 44, 45, 56,
         57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
         74, 75, 76, 77, 78, 79, 80, 81, 82, 83], dtype=int64)              ]
 [array([46, 47, 48, 49, 50, 51], dtype=int64)]

[0 2 2 2 0 0 0 1 1 1 1 1 1 1 1 1 0 0 4 4 4 4 4 0 3 3 3 0 0 0 5 5 5 5 4 3 0]
37
[-1  0  1  2  3  4]
[[array([ 7,  8,  9, 10, 11, 12, 13, 14, 15], dtype=int64)]
 [array([1, 2, 3], dtype=int64)]
 [array([24, 25, 26, 35], dtype=int64)]
 [array([18, 19, 20, 21, 22, 34], dtype=int64)]
 [array([30, 31, 32, 33], dtype=int64)]]
files_clusters_index_array_of_only_one_image:  [(array([ 0,  4,  5,  6, 16, 17, 23, 27, 28, 29, 36], dtype=int64),)]
Final List:  [ 0  1  4  5  6 12 16 17 23 24 27 28 29 30 34 36]
[0 0 0 0 0 0 0 0 1 0 0 0 2 0 0 0 0 1 1 1 1 1 1 0 0 2 2 2 2 0 0 0]
32
[-1  0  1]
[[array([ 8, 17, 18, 19, 20, 21, 22], dtype=int64)]
 [array([12, 25, 26, 27, 28], dtype=int64)]]
files_clusters_index_array_of_only_one_image:  [(array([ 0,  1,  2,  3,  4,  5,  6,  7,  9, 10, 11, 13, 14, 15, 16, 23, 24,
       29, 30, 31], dtype=int64),)]
Final List:  [ 0  1  2  3  4  5  6  7  9 10 11 13 14 15 16 22 23 24 28 29 30 31]
[0 2 2 2 2 2 0 3 3 3 3 3 3 3 3 0 0 0 0 2 2 2 2 2 2 2 2 2 2 0 0 0 0 1 1 1 1
 1 1 1

[3 3 3 3 3 0 0 0 0 0 0 0 0 0 4 0 4 2 2 2 4 4 1 0 1 1 1 1 1 1 1 1 1 0 0 0 0
 0 4 4 4 0 0 4 4 0 0 0 0]
49
[-1  0  1  2  3]
[[array([22, 24, 25, 26, 27, 28, 29, 30, 31, 32], dtype=int64)]
 [array([17, 18, 19], dtype=int64)]
 [array([0, 1, 2, 3, 4], dtype=int64)]
 [array([14, 16, 20, 21, 38, 39, 40, 43, 44], dtype=int64)]]
files_clusters_index_array_of_only_one_image:  [(array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 15, 23, 33, 34, 35, 36, 37, 41,
       42, 45, 46, 47, 48], dtype=int64),)]
Final List:  [ 1  5  6  7  8  9 10 11 12 13 15 16 18 23 24 33 34 35 36 37 41 42 45 46
 47 48]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
26
[-1]
[]
files_clusters_index_array_of_only_one_image:  [(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25], dtype=int64),)]
Final List:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
[3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 0 0 0 0 3 3

### Finding Laplacian Score of Frames for Analysis

In [59]:
import cv2
import numpy as np
def variance_of_laplacian(image):
        return cv2.Laplacian(image, cv2.CV_64F).var()
    
    
path = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_Hist_Others\\VID28\\final_images\\test_2.jpeg"
img_file = cv2.imread(path)
img = cv2.cvtColor(img_file, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_HIST_2_2\\VID1\\final_images\\test_0.jpeg"
img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID29\\final_images\\test_21.jpeg"

img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID30\\final_images\\test_32.jpeg"

img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID30\\final_images\\test_77.jpeg"

img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID30\\final_images\\test_0.jpeg"

img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID30\\final_images\\test_8.jpeg"

img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID29\\final_images\\test_21.jpeg"

img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID30\\final_images\\test_65.jpeg"

img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID30\\final_images\\test_74.jpeg"

img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

path = "C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID30\\final_images\\test_58.jpeg"

img_file2 = cv2.imread(path)
img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
var_lap = variance_of_laplacian(img2)
print(var_lap)

print("VID29: 24 -> 32")

for i in range(24, 33):
    path = f"C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID29\\final_images\\test_{i}.jpeg"
    img_file2 = cv2.imread(path)
    img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
    var_lap = variance_of_laplacian(img2)
    print(var_lap)

var_laps = []
print("VID34")
for i in range(0,28):
    path = f"C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID34\\final_images\\test_{i}.jpeg"
    img_file2 = cv2.imread(path)
    img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
    var_laps.append(var_lap)
    var_lap = variance_of_laplacian(img2)
    print(var_lap)
    print(np.mean(np.array(var_laps)))
    
print("VID28")
for i in range(0,28):
    path = f"C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID28\\final_images\\test_{i}.jpeg"
    img_file2 = cv2.imread(path)
    img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
    var_lap = variance_of_laplacian(img2)
    print(var_lap)
    
# print("VID29")
# for i in range(0,12):
#     path = f"C:\\Users\\KIIT\\Desktop\\College\\Animall\\key_frame_extraction_public-master\\VID29\\final_images\\test_{i}.jpeg"
#     img_file2 = cv2.imread(path)
#     img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
#     var_lap = variance_of_laplacian(img2)
#     print(var_lap)
    
var_laps = []
print("VID29 part2")
for i in range(0,33):
    path = f"C:\\Users\\KIIT\\Desktop\\Videos\\Manual Assessment Videos [LUV+DCT]\\VID29\\final_images\\test_{i}.jpeg"
    img_file2 = cv2.imread(path)
    img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
    var_lap = variance_of_laplacian(img2)
    var_laps.append(var_lap)
    print(var_lap)
    print(np.mean(np.array(var_laps)))
    
# print("VID29 part2")
# for i in range(0,29):
#     path = f"C:\\Users\\KIIT\\Desktop\\College\\Animall\\key_frame_extraction_public-master\\VID4\\final_images\\test_{i}.jpeg"
#     img_file2 = cv2.imread(path)
#     img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
#     var_lap = variance_of_laplacian(img2)
#     var_laps.append(var_lap)
#     print(var_lap)
#     print(np.mean(np.array(var_laps)))
    
    
print("VID28 New")
for i in range(0,43):
    path = f"C:\\Users\\KIIT\\Desktop\\College\\Animall\\key_frame_extraction_public-master\\VID28\\final_images\\test_{i}.jpeg"
    img_file2 = cv2.imread(path)
    img2 = cv2.cvtColor(img_file2, cv2.COLOR_BGR2GRAY)
    var_lap = variance_of_laplacian(img2)
    var_laps.append(var_lap)
    print(var_lap)
    print(np.mean(np.array(var_laps)))

258.45658993484227
3562.5658928446824
321.82347586142356
185.68834393164494
972.2163053377046
536.4632016702811
1086.257961968316
321.82347586142356
318.57977097791957
624.483077208919
1186.0314927288848
VID29: 24 -> 32
162.60020034177802
170.89264044279224
187.29465157602897
490.87469547892107
378.0121348956154
152.746596668501
144.8911962255656
128.1619770732694
132.15013758948473
VID34
91.83797910908632
132.15013758948473
100.2099425344841
111.99405834928552
10.142592295626462
108.0660197443517
116.59225670219574
83.5851628821704
133.07555912703313
90.18658164617547
91.12034754846285
97.33474455965175
95.65320994294136
96.44697355805333
77.4213203880195
96.34775310616433
68.97337454083161
94.24481613748156
74.25724099738774
91.71767197781658
96.31344261007217
90.13036007050486
69.94037905071661
90.64561694880213
62.952309988934964
89.0529063412571
61.25208285108026
87.18857803037695
85.03313031145865
85.45947835175717
103.71415170969854
85.43283159923851
125.40305506534285
86.508203

### Computing Frame Difference and Count for Analysis

In [45]:
import cv2
import numpy as np
path1 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_HIST_2_2\\VID4\\candidate_frames_and_their_cluster_folder\\test_0.jpeg"
path2 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_HIST_2_2\\VID4\\candidate_frames_and_their_cluster_folder\\test_1.jpeg"

img1 = cv2.imread(path1)
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2LUV)
img2 = cv2.imread(path2)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2LUV)

if img1 is not None and img2 is not None:
    # Calculating difference between current and previous frame
    diff = cv2.absdiff(img1, img2)
    count = np.sum(diff)
    print(count)
    
    
path1 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_HIST_2_2\\VID4\\candidate_frames_and_their_cluster_folder\\test_0.jpeg"
path2 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_HIST_2_2\\VID4\\candidate_frames_and_their_cluster_folder\\test_3.jpeg"

img1 = cv2.imread(path1)
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2LUV)
img2 = cv2.imread(path2)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2LUV)

if img1 is not None and img2 is not None:
    # Calculating difference between current and previous frame
    diff = cv2.absdiff(img1, img2)
    count = np.sum(diff)
    print(count)
    
path1 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_HIST_2_2\\VID4\\candidate_frames_and_their_cluster_folder\\test_41.jpeg"
path2 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_HIST_2_2\\VID4\\candidate_frames_and_their_cluster_folder\\test_42.jpeg"

img1 = cv2.imread(path1)
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2LUV)
img2 = cv2.imread(path2)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2LUV)

if img1 is not None and img2 is not None:
    # Calculating difference between current and previous frame
    diff = cv2.absdiff(img1, img2)
    count = np.sum(diff)
    print(count)
    
path1 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_DCT_2_2\\VID6\\final_images\\test_21.jpeg"
path2 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_DCT_2_2\\VID6\\final_images\\test_22.jpeg"

img1 = cv2.imread(path1)
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2LUV)
img2 = cv2.imread(path2)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2LUV)

if img1 is not None and img2 is not None:
    # Calculating difference between current and previous frame
    diff = cv2.absdiff(img1, img2)
    count = np.sum(diff)
    print(count)

path1 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_DCT_2_2\\VID6\\final_images\\test_24.jpeg"
path2 = "C:\\Users\\KIIT\\Desktop\\Videos\\LUV_Man_10_2500_DCT_2_2\\VID6\\final_images\\test_26.jpeg"

img1 = cv2.imread(path1)
img1 = cv2.cvtColor(img1, cv2.COLOR_BGR2LUV)
img2 = cv2.imread(path2)
img2 = cv2.cvtColor(img2, cv2.COLOR_BGR2LUV)

if img1 is not None and img2 is not None:
    # Calculating difference between current and previous frame
    diff = cv2.absdiff(img1, img2)
    count = np.sum(diff)
    print(count)

15812690
22944808
16382073
15367016
18134043
